server:
  port: 8086

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_AUTH_URL:jdbc:postgresql://localhost:5432/auth_service}
    username: ${DB_AUTH_USERNAME:user}
    password: ${DB_AUTH_PASSWORD:123456789abc}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${keycloak.domain}/realms/${keycloak.realm}"

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springdoc:
  api-docs:
    path: /api/v1/auth/api-docs
  swagger-ui:
    path: /api/v1/auth/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

keycloak:
  realm: cab-aggregator
  domain: keycloak:8080
  admin-client-id: admin-client
  admin-client-secret: 8pEFEmfOofwarXWWUYtjglwYUwoonHv3
  client: authenticationClientId
  auth-server-url: http://${keycloak.domain}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
