scrape_configs:

  - job_name: eureka-service-metrics
    static_configs:
      - targets: [ "host.docker.internal:8761", "eureka-service:8761" ]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 60s

  - job_name: gateway-service-metrics
    static_configs:
      - targets: [ "host.docker.internal:9090", "gateway-service:9090" ]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 60s

  - job_name: "passenger-service-metrics"
    static_configs:
      - targets: [ "passenger-service:8081" ]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 60s

  - job_name: "driver-service-metrics"
    static_configs:
      - targets: [ "driver-service:8082" ]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 60s

  - job_name: "rides-service-metrics"
    static_configs:
      - targets: [ "rides-service:8083" ]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 60s

  - job_name: "rates-service-metrics"
    static_configs:
      - targets: [ "rates-service:8084" ]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 60s

  - job_name: "auth-service-metrics"
    static_configs:
      - targets: [ "auth-service:8086" ]
    metrics_path: "/actuator/prometheus"
    scrape_interval: 60s
