server:
  port: 9090

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://${keycloak.domain}/realms/${keycloak.realm}"
          jwk-set-uri: "http://${keycloak.domain}/realms/${keycloak.realm}/protocol/openid-connect/certs"
  cloud:
    gateway:
      routes:
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**
        - id: rides-service
          uri: lb://rides-service
          predicates:
            - Path=/api/v1/rides/**
        - id: rates-service
          uri: lb://rates-service
          predicates:
            - Path=/api/v1/rates/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/users/**

keycloak:
  realm: ${KEYCLOAK_REALM:cab-aggregator}
  domain: ${KEYCLOAK_DOMAIN:localhost:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
