server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/api/v1/passengers/**
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**
        - id: rides-service
          uri: lb://rides-service
          predicates:
            - Path=/api/v1/rides/**
        - id: rates-service
          uri: lb://rates-service
          predicates:
            - Path=/api/v1/rates/**
